pipeline {
    agent any  // Runs on any available agent (Windows)
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target\\surefire-reports\\*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat 'call jenkins\\scripts\\deliver.bat'
            }
        }
    }
}
