pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target\\surefire-reports\\*.xml'
                }
            }
        }
        stage('Deploy & Run') {
            steps {
                bat 'call jenkins\\scripts\\deliver.bat'
            }
        }
    }
}
